<a href="https://colab.research.google.com/github/henrykibithia8-dev/DS-projests/blob/main/Building_a_decision_tree_classification_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Building a decision tree classification model**

In [1]:
#we import all the packages we will need.
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

**Data**

In this train, the dataset we will be using is the Iris dataset, which is a multivariate dataset where each class refers to a type of Iris plant. This dataset is free and publicly available at the UCI Machine Learning Repository.

This dataset contains a set of 150 records with five attributes:

Sepal length.

Sepal width.

Petal length.

Petal width.

Species – the type of Iris plant we will be classifying.

In [2]:
#Let's import the data to see what we are dealing with
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/classification_sprint/iris.csv')
df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

**Preprocessing**

We will start by preprocessing the data so that we can run it through the model algorithm. This involves:

- Splitting the data into features and labels.
- Standardising the data using `sklearn`'s `StandardScaler`.
- Splitting the data into training and testing data.

In [3]:
# Separate into features and target
y = df["species"]
X = df.drop(["species"], axis = 1)

In [4]:
# Standardise the data
standard_scaler = StandardScaler()
#transformdata
X_transformed = standard_scaler.fit_transform(X)

In [5]:
# Split into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.3, random_state=50)

**Training**

We will now fit a decision tree classification model to our data using sklearn's DecisionTreeClassifier with default parameters and a random state of 42.

In [6]:
#create a classifier instance and fit the data then train
tree = DecisionTreeClassifier(random_state=42)
tree.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

**Testing**

Now let's predict the labels for our test set and examine the performance of our model using a confusion matrix.

In [7]:
y_pred = tree.predict(X_test)

In [8]:
#Let's first see how many of each class we have in this test set:
y_test.value_counts()

species
Iris-versicolor    17
Iris-setosa        14
Iris-virginica     14
Name: count, dtype: int64

In [12]:
labels =  ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
pd.DataFrame(data = confusion_matrix(y_test, y_pred), index = labels, columns = labels)

                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               14                0               0
Iris-versicolor            0               16               1
Iris-virginica             0                1              13

Our model does extremely well! Let's also take a look at the **classification report** for our predicted values.

In [17]:
print(classification_report(y_test, y_pred, target_names=['Iris-setosa', 'Iris-versicolor','Iris-virginica']))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      0.94      0.94        17
 Iris-virginica       0.93      0.93      0.93        14

       accuracy                           0.96        45
      macro avg       0.96      0.96      0.96        45
   weighted avg       0.96      0.96      0.96        45

Building a random forest classification model
We will use the same data used in the decision tree classifier above to train a random forest classifier.

Imports
First, we need to import sklearn's RandomForestClassifier. All other imports needed were declared above.

In [18]:
from sklearn.ensemble import RandomForestClassifier

#### Training

We now fit a random forest classification model to our data using `sklearn`'s `RandomForestClassifier` with default parameters, a **random state** of `42`, and the **number of trees** set to `100`.

In [19]:
forest = RandomForestClassifier(n_estimators=100, random_state=42)
forest.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

#### Testing

As we did with the decision tree model, let's predict the labels for our test set and examine the performance of our model using a confusion matrix.

In [22]:
pred_forest = forest.predict(X_test)

labels = ['Iris-setosa', 'Iris-versicolor','Iris-virginica']
pd.DataFrame(data = confusion_matrix(y_test, pred_forest), index = labels, columns = labels)

                 Iris-setosa  Iris-versicolor  Iris-virginica
Iris-setosa               14                0               0
Iris-versicolor            0               16               1
Iris-virginica             0                1              13

Let's also take a look at the classification report for our predicted values.

In [24]:
print(classification_report(y_test, pred_forest, target_names=['Iris-setosa', 'Iris-versicolor','Iris-virginica']))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.94      0.94      0.94        17
 Iris-virginica       0.93      0.93      0.93        14

       accuracy                           0.96        45
      macro avg       0.96      0.96      0.96        45
   weighted avg       0.96      0.96      0.96        45